### ISSUE TITLE
Error with get Line Style by Name

### ISSUE THREAD

**Issue by DanielHurtubise** [ksobon/archi-lab#5]
![image](https://user-images.githubusercontent.com/4299930/37139458-3af2bbfc-22ae-11e8-8027-e13d7c7aec5e.png)

**Comment by ksobon** [comment]
Seems to be working fine on my end: 

![image](https://user-images.githubusercontent.com/529781/37161342-6526062e-22c0-11e8-94e5-6f3f66056631.png)
